### ISSUE TITLE
Marketing Node Import Broken in Latest Version

### ISSUE THREAD

**Issue by stolinski** [mailchimp/mailchimp-client-lib-codegen#162]
Using https://github.com/mailchimp/mailchimp-marketing-node

After updating, we're now seeing 

```
exports.prototype.setConfig = function(config = {}) {
                  ^
TypeError: Cannot set property 'setConfig' of undefined
    at node_modules/@mailchimp/mailchimp_marketing/src/ApiClient.js (/Users/scotttolinski/Sites/levelup/api/node_modules/@mailchimp/mailchimp_marketing/src/ApiClient.js:144:19)
    at __require (/Users/scotttolinski/Sites/levelup/api/dist/index.js:9:44)
    at node_modules/@mailchimp/mailchimp_marketing/src/index.js (/Users/scotttolinski/Sites/levelup/api/node_modules/@mailchimp/mailchimp_marketing/src/index.js:1:17)
    at __require (/Users/scotttolinski/Sites/levelup/api/dist/index.js:9:44)
    at Object.<anonymous> (/Users/scotttolinski/Sites/levelup/api/src/users/methods.ts:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at main (/Users/scotttolinski/Sites/levelup/api/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/Users/scotttolinski/Sites/levelup/api/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

**Comment by bipol-mc** [comment]
Hey @stolinski, sorry to hear about the difficulties you're experiencing here.

Could you pass along your node version, as well as a [short example](http://sscce.org/) if you have one? 

I may be missing something here, but I'm having trouble reproducing using these versions and this script locally:
```sh
bipolalam@MacBook-Pro bipolapp % npm list
***
├── @mailchimp/mailchimp_marketing@3.0.42
├── body-parser@1.19.0
├── csv@5.5.0
├── express@4.17.1
├── md5@2.3.0
├── node-fetch@2.6.1
└── querystring@0.2.1

bipolalam@MacBook-Pro bipolapp % node -v
v16.2.0
```

```js
import mailchimp from "@mailchimp/mailchimp_marketing";

mailchimp.setConfig({
  apiKey: "***-us17",
  server: "us17",
});

async function run() {
  const response = await mailchimp.ping.get();
  console.log(response);
}

run();
```

**Comment by kstolte** [comment]
@bipol-mc https://github.com/kstolte/MailChimpIssue162

**Comment by bipol-mc** [comment]
Hey @kstolte - thank you so much for the example!

I think the problem here is that the node library does not expose a default export.  

If you import mailchimp as
```
import * as mailchimp from "@mailchimp/mailchimp_marketing";
```
In [mailchimpPing.js](https://github.com/kstolte/MailChimpIssue162/blob/master/src/mailchimpPing.js#L1), the example should work as expected.

**Comment by kstolte** [comment]
thanks @bipol-mc. I ended up just changing it to a require instead of import.

your import above works when it is .js but there is a different error if it is adjusted to be a .ts file.


```
/mailchimp162/node_modules/ts-node/src/index.ts:587
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/mailchimpPing.ts:1:23 - error TS2306: File '/mailchimp162/node_modules/@mailchimp/mailchimp_marketing/types.d.ts' is not a module.

1 import mailchimp from "@mailchimp/mailchimp_marketing";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/mailchimp162/node_modules/ts-node/src/index.ts:587:12)
    at reportTSError (/mailchimp162/node_modules/ts-node/src/index.ts:591:19)
    at getOutput (/mailchimp162/node_modules/ts-node/src/index.ts:921:36)
    at Object.compile (/mailchimp162/node_modules/ts-node/src/index.ts:1189:32)
    at Module.m._compile (/mailchimp162/node_modules/ts-node/src/index.ts:1295:42)
```

For anyone else playing at home:
**In both cases the error is resolved by doing the require syntax.**

I think this can be closed @bipol-mc.
Thanks much!

**Comment by bipol-mc** [comment]
Awesome!  I'll be closing this for now, but please feel free to reopen a new issue if things are still not working as expected.

Thanks y'all.

**Comment by minlare** [comment]
I've just come across this issue myself when trying to `import mailchimp from "@mailchimp/mailchimp_marketing";` in a netlify typescript function.

Error message was `Cannot set properties of undefined (setting 'setConfig')`

I've managed to import successfully by changing the name of the `exports` prototype object to `exportsTest` throughout the `src/ApiClient.js` file.

![image](https://user-images.githubusercontent.com/1862882/146569529-94196612-fb4d-4dcc-8348-8360dd13aeab.png)

In light of this, I believe you need to update all instances of `exports` (except `module.exports`) to another variable name in  `https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/main/swagger-config/marketing/javascript/templates/ApiClient.mustache`
